version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: airflow
      MYSQL_DATABASE: airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - airflow_network

  airflow-webserver:
    image: apache/airflow:latest
    depends_on:
      - mysql
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: 'mysql+mysqldb://airflow:airflow@mysql/airflow'
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8181:8080"
    command: /bin/bash -c "sleep 10 && airflow webserver"
    restart: always
    networks:
      - airflow_network

  airflow-scheduler:
    image: apache/airflow:latest
    depends_on:
      - mysql
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: 'mysql+mysqldb://airflow:airflow@mysql/airflow'
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: /bin/bash -c "sleep 10 && airflow scheduler"
    restart: always
    networks:
      - airflow_network

  airflow-init:
    image: apache/airflow:latest
    depends_on:
      - mysql
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: 'mysql+mysqldb://airflow:airflow@mysql/airflow'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    entrypoint: /bin/bash -c "sleep 10 && airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com"
    restart: always
    networks:
      - airflow_network

volumes:
  mysql_data:

networks:
  airflow_network:
    driver: bridge
