version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: airflow
      MYSQL_DATABASE: airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - airflow-network

  airflow-webserver:
    image: apache/airflow:latest
    depends_on:
      - mysql
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: 'mysql+mysqlconnector://airflow:airflow@mysql/airflow'
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8181:8080"
    command: webserver
    restart: always
    networks:
      - airflow-network

  airflow-scheduler:
    image: apache/airflow:latest
    depends_on:
      - mysql
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: 'mysql+mysqlconnector://airflow:airflow@mysql/airflow'
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler
    restart: always
    networks:
      - airflow-network

  airflow-init:
    image: apache/airflow:latest
    depends_on:
      - mysql
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: 'mysql+mysqlconnector://airflow:airflow@mysql/airflow'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt
    entrypoint: /bin/bash -c "airflow db init && pip install -r /requirements.txt && airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com"
    restart: always
    networks:
      - airflow-network

volumes:
  mysql_data:

networks:
  airflow-network:
    driver: bridge